2021-05-20 10:01:37,286---INFO---server.py---HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2021-05-20 10:01:37,286---INFO---server.py---Configuring endpoint tcp:port=8000:interface=127.0.0.1
2021-05-20 10:01:37,288---INFO---server.py---Listening on TCP address 127.0.0.1:8000
2021-05-20 10:01:38,450---INFO---runserver.py---WebSocket HANDSHAKING /monitor/ [127.0.0.1:47820]
2021-05-20 10:01:38,450---DEBUG---http_protocol.py---Upgraded connection ['127.0.0.1', 47820] to WebSocket
2021-05-20 10:01:38,452---INFO---runserver.py---WebSocket HANDSHAKING /monitor/ [127.0.0.1:47822]
2021-05-20 10:01:38,452---DEBUG---http_protocol.py---Upgraded connection ['127.0.0.1', 47822] to WebSocket
2021-05-20 10:01:38,453---INFO---runserver.py---WebSocket HANDSHAKING /monitor/ [127.0.0.1:47824]
2021-05-20 10:01:38,454---DEBUG---http_protocol.py---Upgraded connection ['127.0.0.1', 47824] to WebSocket
2021-05-20 10:01:38,455---INFO---runserver.py---WebSocket HANDSHAKING /monitor/ [127.0.0.1:47826]
2021-05-20 10:01:38,455---DEBUG---http_protocol.py---Upgraded connection ['127.0.0.1', 47826] to WebSocket
2021-05-20 10:01:38,477---DEBUG---connection.py---Creating tcp connection to ('127.0.0.1', 6379)
2021-05-20 10:01:38,477---DEBUG---connection.py---Creating tcp connection to ('127.0.0.1', 6379)
2021-05-20 10:01:38,477---DEBUG---connection.py---Creating tcp connection to ('127.0.0.1', 6379)
2021-05-20 10:01:38,478---DEBUG---connection.py---Creating tcp connection to ('127.0.0.1', 6379)
2021-05-20 10:01:38,478---DEBUG---connection.py---Creating tcp connection to ('127.0.0.1', 6379)
2021-05-20 10:01:38,480---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47820] open and established
2021-05-20 10:01:38,480---INFO---runserver.py---WebSocket CONNECT /monitor/ [127.0.0.1:47820]
2021-05-20 10:01:38,480---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47820] accepted by application
2021-05-20 10:01:38,480---INFO---consumers.py---=====> agents: {'celular-cam2': 1}
2021-05-20 10:01:38,480---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47822] open and established
2021-05-20 10:01:38,480---INFO---runserver.py---WebSocket CONNECT /monitor/ [127.0.0.1:47822]
2021-05-20 10:01:38,481---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47822] accepted by application
2021-05-20 10:01:38,481---INFO---consumers.py---=====> agents: {'celular-cam2': 1, 'celular-cam5': 0}
2021-05-20 10:01:38,481---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47824] open and established
2021-05-20 10:01:38,481---INFO---runserver.py---WebSocket CONNECT /monitor/ [127.0.0.1:47824]
2021-05-20 10:01:38,481---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47824] accepted by application
2021-05-20 10:01:38,481---INFO---consumers.py---=====> agents: {'celular-cam2': 1, 'celular-cam5': 0, 'celular-cam3': 0}
2021-05-20 10:01:38,482---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47826] open and established
2021-05-20 10:01:38,482---INFO---runserver.py---WebSocket CONNECT /monitor/ [127.0.0.1:47826]
2021-05-20 10:01:38,482---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 47826] accepted by application
2021-05-20 10:01:38,482---INFO---consumers.py---=====> agents: {'celular-cam2': 1, 'celular-cam5': 0, 'celular-cam3': 0}
2021-05-20 10:01:59,164---DEBUG---http_protocol.py---HTTP b'GET' request for ['127.0.0.1', 48016]
2021-05-20 10:01:59,240---DEBUG---http_protocol.py---HTTP 200 response started for ['127.0.0.1', 48016]
2021-05-20 10:01:59,241---DEBUG---http_protocol.py---HTTP close for ['127.0.0.1', 48016]
2021-05-20 10:01:59,241---DEBUG---http_protocol.py---HTTP response complete for ['127.0.0.1', 48016]
2021-05-20 10:01:59,241---INFO---runserver.py---[mHTTP GET /monitor/ 200 [0.08, 127.0.0.1:48016][0m
2021-05-20 10:01:59,474---INFO---runserver.py---WebSocket HANDSHAKING /monitor/ [127.0.0.1:48022]
2021-05-20 10:01:59,474---DEBUG---http_protocol.py---Upgraded connection ['127.0.0.1', 48022] to WebSocket
2021-05-20 10:01:59,478---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 48022] open and established
2021-05-20 10:01:59,479---INFO---runserver.py---WebSocket CONNECT /monitor/ [127.0.0.1:48022]
2021-05-20 10:01:59,479---DEBUG---ws_protocol.py---WebSocket ['127.0.0.1', 48022] accepted by application
2021-05-20 10:01:59,494---INFO---consumers.py---=====> Msg enviada: {'type': 'send_message', 'event': 'inventory', 'agents': [['celular-cam2', 1], ['celular-cam5', 0], ['celular-cam3', 0]]}
2021-05-20 10:01:59,494---DEBUG---ws_protocol.py---Sent WebSocket packet to client for ['127.0.0.1', 48022]
2021-05-20 10:02:33,926---DEBUG---http_protocol.py---HTTP b'GET' request for ['127.0.0.1', 48324]
2021-05-20 10:02:33,930---INFO---views.py---=====> /views/agent_ask_processing_rate (<ASGIRequest: GET '/monitor/agent/celular-cam3/ask-processing-rate/ed673c32-78f6-4725-9937-840616b494b0'>, 'celular-cam3', 'ed673c32-78f6-4725-9937-840616b494b0')
2021-05-20 10:02:33,987---ERROR---log.py---Internal Server Error: /monitor/agent/celular-cam3/ask-processing-rate/ed673c32-78f6-4725-9937-840616b494b0
Traceback (most recent call last):
  File "/home/gleison/gteccom-cercainteligente/2.0.1/lib/python3.8/site-packages/asgiref/sync.py", line 458, in thread_handler
    raise exc_info[1]
  File "/home/gleison/gteccom-cercainteligente/2.0.1/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/gleison/gteccom-cercainteligente/2.0.1/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gleison/gteccom-cercainteligente/2.0.1/lib/python3.8/site-packages/asgiref/sync.py", line 423, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/gleison/gteccom-cercainteligente/2.0.1/lib/python3.8/site-packages/asgiref/sync.py", line 462, in thread_handler
    return func(*args, **kwargs)
  File "/home/gleison/gteccom-cercainteligente/server/monitor/views.py", line 83, in agent_ask_processing_rate
    Group('agent').send({
NameError: name 'Group' is not defined
2021-05-20 10:02:33,989---DEBUG---http_protocol.py---HTTP 500 response started for ['127.0.0.1', 48324]
2021-05-20 10:02:33,989---DEBUG---http_protocol.py---HTTP response chunk for ['127.0.0.1', 48324]
2021-05-20 10:02:33,989---DEBUG---http_protocol.py---HTTP close for ['127.0.0.1', 48324]
2021-05-20 10:02:33,990---DEBUG---http_protocol.py---HTTP response complete for ['127.0.0.1', 48324]
2021-05-20 10:02:33,990---ERROR---runserver.py---[35;1mHTTP GET /monitor/agent/celular-cam3/ask-processing-rate/ed673c32-78f6-4725-9937-840616b494b0 500 [0.06, 127.0.0.1:48324][0m
2021-05-20 10:04:48,734---DEBUG---ws_protocol.py---WebSocket incoming frame on ['127.0.0.1', 47820]
2021-05-20 10:04:48,734---INFO---consumers.py---=====> Msg recebida: {"type": "agent-update", "target-groups": ["monitor"], "who": "celular-cam2", "camera_running": 0}
